name: shellcheck

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.sh'
      - docs/part**.md
      - .github/workflows/shellcheck.yml
  push:
    branches:
      - master
    paths:
      - '**.sh'
      - docs/part**.md
      - .github/workflows/shellcheck.yml

jobs:
  shellcheck-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract commands from markdown files
        run: |
          set -eux
          echo '#!/usr/bin/env bash' > README.sh
          find . -name '*.md' -print0 | while IFS= read -r -d '' FILE ; do
            sed -n "/^\`\`\`\(bash\|shell\).*/,/^\`\`\`$/p" "${FILE}" \
            | \
            sed \
              -e 's/^```\(bash\|shell\).*/\n/' \
              -e 's/^```$//' \
            >> README.sh
          done

      - name: Lint check
        uses: azohra/shell-linter@v0.4.0
